import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import NavBar from "../components/navbar";
import UserAuthContextProvider from "../Context/UserAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Healthcare App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}
>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {/*Body*/}
      
        <main>
          <UserAuthContextProvider>
          {children}
          </UserAuthContextProvider>
        </main>
          
      </body>
    </html>
  );
}
