import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import UserAuthContext from "../Context/UserAuthContext";
import NavBar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Healthcare App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}
>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserAuthContext>
      <NavBar />
      {/*Body*/}
      <main>
        {children}
      </main>
      </UserAuthContext>
      </body>
    </html>
  );
}
